name: Telegram notify action

on:
  push
#  pull_request_review_comment:
#    types: [ created ]
jobs:
  send-telegram-notification:
#    runs-on: ubuntu-latest
#    if: always()
#    steps:
#      - name: 'Send telegram notification'
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TG_TO }}
#          token: ${{ secrets.TG_TOKEN }}
#          message: |
#            The ${{ github.event_name.repository.name }} PR commnets.
#             ${{ github.event.comment.body }}.


  - name: Telegram deploy finished without problems
    uses: appleboy/telegram-action@master
    with:
      to: ${{ secrets.TG_TO }}
      token: ${{ secrets.TG_TOKEN }}
      args: Everything work perfectly, you can be happy and rest.
